coldfront/config/urls.py
# SPDX-FileCopyrightText: (C) ColdFront Authors
#
# SPDX-License-Identifier: AGPL-3.0-or-later

"""
ColdFront URL Configuration
"""

import environ
import split_settings
from django.conf import settings
from django.contrib import admin
from django.core import serializers
from django.http import HttpResponse
from django.urls import include, path
from django.views.generic import TemplateView

import coldfront.core.portal.views as portal_views
from coldfront.config.env import ENV, PROJECT_ROOT

admin.site.site_header = "ColdFront Administration"
admin.site.site_title = "ColdFront Administration"

urlpatterns = [
    path("admin/", admin.site.urls),
    path("robots.txt", TemplateView.as_view(template_name="robots.txt", content_type="text/plain"), name="robots"),
    path("", portal_views.home, name="home"),
    path("center-summary", portal_views.center_summary, name="center-summary"),
    path("allocation-summary", portal_views.allocation_summary, name="allocation-summary"),
    path("allocation-by-fos", portal_views.allocation_by_fos, name="allocation-by-fos"),
    path("user/", include("coldfront.core.user.urls")),
    path("portal/", include("coldfront.core.portal.urls")),
    path("project/", include("coldfront.core.project.urls")),
    path("allocation/", include("coldfront.core.allocation.urls")),
    path("resource/", include("coldfront.core.resource.urls")),
]

if settings.GRANT_ENABLE:
    urlpatterns.append(path("grant/", include("coldfront.core.grant.urls")))

if settings.PUBLICATION_ENABLE:
    urlpatterns.append(path("publication/", include("coldfront.core.publication.urls")))

if settings.RESEARCH_OUTPUT_ENABLE:
    urlpatterns.append(path("research-output/", include("coldfront.core.research_output.urls")))

if "coldfront.plugins.api" in settings.INSTALLED_APPS:
    urlpatterns.append(path("api/", include("coldfront.plugins.api.urls")))

if "coldfront.plugins.iquota" in settings.INSTALLED_APPS:
    urlpatterns.append(path("iquota/", include("coldfront.plugins.iquota.urls")))

if "mozilla_django_oidc" in settings.INSTALLED_APPS:
    urlpatterns.append(path("oidc/", include("mozilla_django_oidc.urls")))

if "coldfront.plugins.slurm" in settings.INSTALLED_APPS:
    urlpatterns.append(path("slurm/", include("coldfront.plugins.slurm.urls")))

if "django_su.backends.SuBackend" in settings.AUTHENTICATION_BACKENDS:
    urlpatterns.append(path("su/", include("django_su.urls")))


def export_as_json(modeladmin, request, queryset):
    response = HttpResponse(content_type="application/json")
    serializers.serialize("json", queryset, stream=response)
    return response


admin.site.add_action(export_as_json, "export_as_json")

# Local urls overrides
local_urls = [
    # Local urls relative to coldfront.config package
    "local_urls.py",
    # System wide urls for production deployments
    "/etc/coldfront/local_urls.py",
    # Local urls relative to coldfront project root
    PROJECT_ROOT("local_urls.py"),
]

if ENV.str("COLDFRONT_URLS", default="") != "":
    # Local urls from path specified via environment variable
    local_urls.append(environ.Path(ENV.str("COLDFRONT_URLS"))())

for lu in local_urls:
    split_settings.tools.include(split_settings.tools.optional(lu))

coldfront/core/allocation/urls.py
# SPDX-FileCopyrightText: (C) ColdFront Authors
#
# SPDX-License-Identifier: AGPL-3.0-or-later

from django.urls import path

import coldfront.core.allocation.views as allocation_views
from coldfront.config.core import ALLOCATION_EULA_ENABLE

urlpatterns = [
    path("", allocation_views.AllocationListView.as_view(), name="allocation-list"),
    path("project/<int:project_pk>/create", allocation_views.AllocationCreateView.as_view(), name="allocation-create"),
    path("<int:pk>/", allocation_views.AllocationDetailView.as_view(), name="allocation-detail"),
    path(
        "change-request/<int:pk>/",
        allocation_views.AllocationChangeDetailView.as_view(),
        name="allocation-change-detail",
    ),
    path(
        "<int:pk>/delete-attribute-change",
        allocation_views.AllocationChangeDeleteAttributeView.as_view(),
        name="allocation-attribute-change-delete",
    ),
    path("<int:pk>/add-users", allocation_views.AllocationAddUsersView.as_view(), name="allocation-add-users"),
    path("<int:pk>/remove-users", allocation_views.AllocationRemoveUsersView.as_view(), name="allocation-remove-users"),
    path("request-list", allocation_views.AllocationRequestListView.as_view(), name="allocation-request-list"),
    path("change-list", allocation_views.AllocationChangeListView.as_view(), name="allocation-change-list"),
    path("<int:pk>/renew", allocation_views.AllocationRenewView.as_view(), name="allocation-renew"),
    path(
        "<int:pk>/allocationattribute/add",
        allocation_views.AllocationAttributeCreateView.as_view(),
        name="allocation-attribute-add",
    ),
    path("<int:pk>/change-request", allocation_views.AllocationChangeView.as_view(), name="allocation-change"),
    path(
        "<int:pk>/allocationattribute/edit",
        allocation_views.AllocationAttributeEditView.as_view(),
        name="allocation-attribute-edit",
    ),
    path(
        "<int:pk>/allocationattribute/delete",
        allocation_views.AllocationAttributeDeleteView.as_view(),
        name="allocation-attribute-delete",
    ),
    path(
        "<int:pk>/allocationnote/add", allocation_views.AllocationNoteCreateView.as_view(), name="allocation-note-add"
    ),
    path(
        "allocation-invoice-list", allocation_views.AllocationInvoiceListView.as_view(), name="allocation-invoice-list"
    ),
    path("<int:pk>/invoice/", allocation_views.AllocationInvoiceDetailView.as_view(), name="allocation-invoice-detail"),
    path(
        "allocation/<int:pk>/add-invoice-note",
        allocation_views.AllocationAddInvoiceNoteView.as_view(),
        name="allocation-add-invoice-note",
    ),
    path(
        "allocation-invoice-note/<int:pk>/update",
        allocation_views.AllocationUpdateInvoiceNoteView.as_view(),
        name="allocation-update-invoice-note",
    ),
    path(
        "allocation/<int:pk>/invoice/delete/",
        allocation_views.AllocationDeleteInvoiceNoteView.as_view(),
        name="allocation-delete-invoice-note",
    ),
    path(
        "add-allocation-account/", allocation_views.AllocationAccountCreateView.as_view(), name="add-allocation-account"
    ),
    path(
        "allocation-account-list/", allocation_views.AllocationAccountListView.as_view(), name="allocation-account-list"
    ),
]

if ALLOCATION_EULA_ENABLE:
    urlpatterns.append(
        path("<int:pk>/review-eula", allocation_views.AllocationEULAView.as_view(), name="allocation-review-eula")
    )

coldfront/core/allocation/models.py
# SPDX-FileCopyrightText: (C) ColdFront Authors
#
# SPDX-License-Identifier: AGPL-3.0-or-later

import datetime
import logging
from enum import Enum

from django.contrib.auth import get_user_model
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.db import models
from django.urls import reverse
from django.utils.html import escape, format_html
from django.utils.module_loading import import_string
from django.utils.safestring import SafeString
from model_utils.models import TimeStampedModel
from simple_history.models import HistoricalRecords

import coldfront.core.attribute_expansion as attribute_expansion
from coldfront.config.core import ALLOCATION_EULA_ENABLE
from coldfront.core.allocation.signals import allocation_activate_user, allocation_remove_user
from coldfront.core.project.models import Project, ProjectPermission
from coldfront.core.resource.models import Resource
from coldfront.core.utils.common import import_from_settings
from coldfront.core.utils.mail import build_link, send_email_template
from coldfront.core.utils.validate import AttributeValidator

logger = logging.getLogger(__name__)

ALLOCATION_ATTRIBUTE_VIEW_LIST = import_from_settings("ALLOCATION_ATTRIBUTE_VIEW_LIST", [])
ALLOCATION_FUNCS_ON_EXPIRE = import_from_settings("ALLOCATION_FUNCS_ON_EXPIRE", [])
ALLOCATION_RESOURCE_ORDERING = import_from_settings("ALLOCATION_RESOURCE_ORDERING", ["-is_allocatable", "name"])

EMAIL_SENDER = import_from_settings("EMAIL_SENDER")


class AllocationPermission(Enum):
    """An allocation permission stores the user and manager fields of a project."""

    USER = "USER"
    MANAGER = "MANAGER"


class AllocationStatusChoice(TimeStampedModel):
    """A project status choice indicates the status of the project. Examples include Active, Archived, and New.

    Attributes:
        name (str): name of project status choice
    """

    class Meta:
        ordering = [
            "name",
        ]

    class AllocationStatusChoiceManager(models.Manager):
        def get_by_natural_key(self, name):
            return self.get(name=name)

    name = models.CharField(max_length=64)
    objects = AllocationStatusChoiceManager()

    def __str__(self):
        return self.name

    def natural_key(self):
        return (self.name,)


class Allocation(TimeStampedModel):
    """An allocation provides users access to a resource.

    Attributes:
        project (Project): links the project the allocation falls under
        resources (Resource): links resources that this allocation allocates
        status (AllocationStatusChoice): represents the status of the allocation
        quantity (int): indicates the quantity of the resource for the allocation, if applicable
        start_date (Date): indicates the start date of the allocation
        end_date (Date): indicates the end/ expiry date of the allocation
        justification (str): text input from the user containing the justification for why the resource is being allocated
        description (str): description of the allocation
        is_locked (bool): indicates whether or not the allocation is locked
        is_changeable (bool): indicates whether or not the allocation is changeable
    """

    class Meta:
        ordering = [
            "end_date",
        ]

        permissions = (
            ("can_view_all_allocations", "Can view all allocations"),
            ("can_review_allocation_requests", "Can review allocation requests"),
            ("can_manage_invoice", "Can manage invoice"),
        )

    project = models.ForeignKey(
        Project,
        on_delete=models.CASCADE,
    )
    resources = models.ManyToManyField(Resource)
    status = models.ForeignKey(AllocationStatusChoice, on_delete=models.CASCADE, verbose_name="Status")
    quantity = models.IntegerField(default=1)
    start_date = models.DateField(blank=True, null=True)
    end_date = models.DateField(blank=True, null=True)
    justification = models.TextField()
    description = models.CharField(max_length=512, blank=True, null=True)
    is_locked = models.BooleanField(default=False)
    is_changeable = models.BooleanField(default=False)
    history = HistoricalRecords()

    def clean(self):
        """Validates the allocation and raises errors if the allocation is invalid."""

        if self.status.name == "Expired":
            if not self.end_date:
                raise ValidationError("You have to set the end date.")

            if self.end_date > datetime.datetime.now().date():
                raise ValidationError("End date cannot be greater than today.")

            if self.start_date > self.end_date:
                raise ValidationError("End date cannot be greater than start date.")

        elif self.status.name == "Active":
            if not self.start_date:
                raise ValidationError("You have to set the start date.")

            if not self.end_date:
                raise ValidationError("You have to set the end date.")

            if self.start_date > self.end_date:
                raise ValidationError("Start date cannot be greater than the end date.")

    def save(self, *args, **kwargs):
        """Saves the project."""

        if self.pk:
            old_obj = Allocation.objects.get(pk=self.pk)
            if old_obj.status.name != self.status.name and self.status.name == "Expired":
                for func_string in ALLOCATION_FUNCS_ON_EXPIRE:
                    func_to_run = import_string(func_string)
                    func_to_run(self.pk)

        super().save(*args, **kwargs)

    @property
    def expires_in(self):
        """
        Returns:
            int: the number of days until the allocation expires
        """

        return (self.end_date - datetime.date.today()).days

    @property
    def get_information(self) -> SafeString:
        """
        Returns:
            SafeString: the allocation's attribute type, usage out of total value, and usage out of total value as a percentage
        """

        html_string = escape("")
        for attribute in self.allocationattribute_set.select_related(
            "allocation_attribute_type", "allocationattributeusage"
        ).all():
            if attribute.allocation_attribute_type.name in ALLOCATION_ATTRIBUTE_VIEW_LIST:
                html_substring = format_html("{}: {} <br>", attribute.allocation_attribute_type.name, attribute.value)
                html_string += html_substring

            if hasattr(attribute, "allocationattributeusage"):
                try:
                    percent = (
                        round(float(attribute.allocationattributeusage.value) / float(attribute.value) * 10000) / 100
                    )
                except ValueError:
                    percent = "Invalid Value"
                    logger.error(
                        "Allocation attribute '%s' is not an int but has a usage",
                        attribute.allocation_attribute_type.name,
                    )
                except ZeroDivisionError:
                    percent = 100
                    logger.error(
                        "Allocation attribute '%s' == 0 but has a usage", attribute.allocation_attribute_type.name
                    )

                html_substring = format_html(
                    "{}: {}/{} ({} %) <br>",
                    attribute.allocation_attribute_type.name,
                    attribute.allocationattributeusage.value,
                    attribute.value,
                    percent,
                )
                html_string += html_substring

        return html_string

    @property
    def get_resources_as_string(self):
        """
        Returns:
            str: the resources for the allocation
        """

        return ", ".join([ele.name for ele in self.resources.all().order_by(*ALLOCATION_RESOURCE_ORDERING)])

    @property
    def get_resources_as_list(self):
        """
        Returns:
            list[Resource]: the resources for the allocation
        """

        return [ele for ele in self.resources.all().order_by("-is_allocatable")]

    @property
    def get_parent_resource(self):
        """
        Returns:
            Resource: the parent resource for the allocation
        """
        resources = self.resources.select_related("resource_type")
        if len(resources) == 1:
            return resources.first()
        else:
            parent = resources.order_by(*ALLOCATION_RESOURCE_ORDERING).first()
            if parent:
                return parent
            # Fallback
            return resources.first()

    def get_attribute(self, name, expand=True, typed=True, extra_allocations=[]):
        """
        Params:
            name (str): name of the allocation attribute type
            expand (bool): indicates whether or not to return the expanded value with attributes/parameters for attributes with a base type of 'Attribute Expanded Text'
            typed (bool): indicates whether or not to convert the attribute value to an int/ float/ str based on the base AttributeType name
            extra_allocations (list[Allocation]): allocations which are available to reference in the attribute list in addition to those associated with this AllocationAttribute

        Returns:
            str: the value of the first attribute found for this allocation with the specified name
        """

        attr = self.allocationattribute_set.filter(allocation_attribute_type__name=name).first()
        if attr:
            if expand:
                return attr.expanded_value(extra_allocations=extra_allocations, typed=typed)
            else:
                if typed:
                    return attr.typed_value()
                else:
                    return attr.value
        return None

    def set_usage(self, name, value):
        """
        Params:
            name (str): allocation attribute type whose usage to set

coldfront/core/allocation/templates/allocation/allocation_account_list.html
{% extends "common/base.html" %}
{% load crispy_forms_tags %}
{% load static %}


{% block title %}
Allocation Accounts
{% endblock %}


{% block content %}
<h2>Allocation Accounts</h2>

<div class="card mb-3 bg-light">
  <div class="card-body">
    <a class="btn btn-success" href="{% url 'add-allocation-account' %}" role="button"><i class="fas fa-plus" aria-hidden="true"></i> Add Allocation Account</a>
  </div>
</div>

{% if allocationaccount_list %}
  <div class="table-responsive">
    <table class="table table-sm">
      <thead>
        <tr>
          <th scope="col">Name</th>
          <th scope="col">Created</th>
        </tr>
      </thead>
      <tbody>
        {% for account in allocationaccount_list %}
          <tr>
            <td>{{ account.name }}</td>
            <td>{{ account.created }}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
{% else %}
  <div class="alert alert-info">
    You have not added any allocation accounts!
  </div>
{% endif %}
{% endblock %}

coldfront/core/allocation/templates/allocation/allocation_add_users.html
{% extends "common/base.html" %}
{% load crispy_forms_tags %}
{% load static %}


{% block title %}
Add Users to Allocation
{% endblock %}


{% block content %}
<h2>Add users to allocation for project: {{allocation.project.title}}</h2>
<hr>

{% if formset %}
  <div class="card border-light">
    <div class="card-body">
      <form action="{% url 'allocation-add-users' allocation.pk %}" method="post">
        {% csrf_token %}
        <div class="table-responsive">
          <table class="table table-sm table-hover">
            <thead>
              <tr>
                <th>
                  <input type="checkbox" class="check" id="selectAll">
                </th>
                <th scope="col">#</th>
                <th scope="col">Username</th>
                <th scope="col">First Name</th>
                <th scope="col">Last Name</th>
                <th scope="col">Email</th>
              </tr>
            </thead>
            <tbody>
              {% for form in formset %}
                <tr>
                  <td>{{ form.selected }}</td>
                  <td>{{ forloop.counter }}</td>
                  <td>{{ form.username.value }}</td>
                  <td>{{ form.first_name.value }}</td>
                  <td>{{ form.last_name.value }}</td>
                  <td>{{ form.email.value }}</td>
                </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
        {{ formset.management_form }}
        <div>
          <button type="submit" class="btn btn-primary confirm-add"><i class="fas
              fa-user-plus"></i> Add Selected Users to Allocation</button>
          <a class="btn btn-secondary" href="{% url 'allocation-detail' allocation.pk %}" role="button"><i class="fas fa-long-arrow-left" aria-hidden="true"></i>
            Back to Allocation</a>
          <br>
        </div>
      </form>
    </div>
  </div>
{% else %}
  <a class="btn btn-secondary mb-3" href="{% url 'allocation-detail' allocation.pk %}" role="button"><i class="fas fa-long-arrow-left" aria-hidden="true"></i> Back to Allocation</a>
  <div class="alert alert-info">
    All users in project are already in this allocation!
  </div>
{% endif %}

{% endblock %}

coldfront/core/allocation/templates/allocation/allocation_allocationattribute_create.html
{% extends "common/base.html" %}
{% load crispy_forms_tags %}
{% load common_tags %}
{% load static %}


{% block title %}
Add Allocation Attribute
{% endblock %}


{% block content %}
<h2>Adding allocation attribute to {{allocation.get_parent_resource}} for PI {{ allocation.project.pi.first_name }}
  {{ allocation.project.pi.last_name }} ({{ allocation.project.pi.username }})</h2>

<form method="post">
  {% csrf_token %}
  {{form |crispy}}
  <input class="btn btn-success" type="submit" value="Add" />
  <a class="btn btn-secondary" href="{% url 'allocation-detail' allocation.pk %}" role="button">Back to
    Allocation</a><br>
</form>
{% endblock %}

coldfront/core/allocation/templates/allocation/allocation_change_list.html
{% extends "common/base.html" %}
{% load crispy_forms_tags %}
{% load common_tags %}
{% load static %}


{% block title %}
Allocation Review New and Pending Change Requests
{% endblock %}


{% block content %}
<h2>Allocation Change Requests</h2>

<hr>

<p class="text-justify">
  For each allocation change request below, there is the option to activate the allocation request and to view the allocation change's detail page.
  If a change request is only for an extension to the allocation, they can be approved on this page. However if the change request includes changes to
  the allocation's attributes, the request must be reviewed and acted upon in its detail page.
</p>

{% if allocation_change_list %}
  <div class="table-responsive">
    <table class="table table-sm">
      <thead>
        <tr>
          <th scope="col">#</th>
          <th scope="col">Requested</th>
          <th scope="col">Project Title</th>
          <th scope="col">Allocation ID</th>
          <th scope="col">PI</th>
          <th scope="col">Resource</th>
          <th scope="col">Extension</th>
          <th scope="col">Actions</th>
        </tr>
      </thead>
      <tbody>
        {% for change in allocation_change_list %}
          <tr>
            <td>{{change.pk}}</td>
            <td>{{ change.created|date:"M. d, Y" }}</td>
            <td><a href="{% url 'project-detail' change.allocation.project.pk %}">{{change.allocation.project.title|truncatechars:50}}</a></td>
            <td><a href="{% url 'allocation-detail' change.allocation.pk %}">{{change.allocation.pk}}</a></td>
            <td>{{change.allocation.project.pi.first_name}} {{change.allocation.project.pi.last_name}}
              ({{change.allocation.project.pi.username}})</td>
            <td>{{change.allocation.get_parent_resource}}</td>
            <td>
              {% if change.end_date_extension == 0 %}
              {% else %} {{change.end_date_extension}} days
              {% endif %}
            </td>
            <td class="text-nowrap">
                <form method="post" action="{% url 'allocation-change-detail' change.pk %}">
              {% if change.allocationattributechangerequest_set.all %}
                <button class="btn btn-success mr-1" aria-disabled="true"
                style="
                      cursor: not-allowed;
                      opacity: 0.6;
                      pointer-events: none;">
                      Approve
                </button>
              {% else %}
                  {% csrf_token %}
                  <input type="hidden" name="end_date_extension" value="{{ change.end_date_extension }}" />
                  <button type="submit" name="action" value="approve" class="btn btn-success mr-1">Approve</button>
              {% endif %}
                <a href="{% url 'allocation-change-detail' change.pk %}" class="btn btn-primary mr-1">Details</a>
                </form>
            </td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
{% else %}
  <div class="alert alert-info">
    No new or pending allocation change requests!
  </div>
{% endif %}

{% endblock %}

coldfront/core/allocation/templates/allocation/allocation_delete_invoice_note.html
{% extends "common/base.html" %}
{% load crispy_forms_tags %}
{% load static %}

{% block title %}
Delete Allocation Invoice Note
{% endblock %}


{% block content %}
<h3>Delete invoice notes for allocation to {{allocation.get_resources_as_string}} for PI
  {{allocation.project.pi.username}}</h3>
<hr>

<div class="card border-light">
  <div class="card-body">
    <form action="{% url 'allocation-delete-invoice-note' allocation.pk %}" method="post">
      {% csrf_token %}
      <div class="table-responsive">
        <table class="table table-sm table-hover">
          <thead>
            <tr>
              <th>
                <input type="checkbox" class="check" id="selectAll">
              </th>
              <th scope="col">Note</th>
              <th scope="col">Author</th>
            </tr>
          </thead>
          <tbody>
            {% for form in formset %}
              <tr>
                <td>{{ form.selected }}</td>
                <td>{{ form.note.value }}</td>
                <td>{{ form.author.value }}</td>
              </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
      {{ formset.management_form }}
      <div>
        <button type="submit" class="btn btn-danger">Delete</button>
        <a class="btn btn-secondary" href="{% url 'allocation-invoice-detail' allocation.pk %}" role="button"><i
            class="fas fa-long-arrow-left" aria-hidden="true"></i> Cancel</a>
        <br>
      </div>
    </form>
  </div>
</div>

{% endblock %}

coldfront/core/allocation/templates/allocation/allocation_invoice_list.html
{% extends "common/base.html" %}
{% load crispy_forms_tags %}
{% load static %}


{% block title %}
Allocation Invoice List
{% endblock %}


{% block content %}
<h2>Allocations that require payment</h2>

{% if allocation_list %}
  <div class="table-responsive">
    <table class="table table-sm">
      <thead>
        <tr>
          <th scope="col">ID</th>
          <th scope="col">Resource</th>
          <th scope="col">Status</th>
          <th scope="col">PI</th>
        </tr>
      </thead>
      <tbody>
        {% for allocation in allocation_list %}
          <tr>
            <td><a href="{% url 'allocation-invoice-detail' allocation.pk %}">{{allocation.pk}}</a></td>
            <td>{{allocation.get_resources_as_string}}</td>
            <td>{{allocation.status}}</td>
            <td>{{allocation.project.pi.username }}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
{% else %}
  <div class="alert alert-info">
    No allocations requiring payment!
  </div>
{% endif %}
{% endblock %}

coldfront/core/allocation/templates/allocation/allocation_note_create.html
{% extends "common/base.html" %}
{% load crispy_forms_tags %}
{% load common_tags %}
{% load static %}


{% block title %}
Add Allocation Notification
{% endblock %}


{% block content %}
<h2>Adding notification to {{allocation.get_parent_resource}} for PI {{ allocation.project.pi.first_name }}
  {{ allocation.project.pi.last_name }} ({{ allocation.project.pi.username }})</h2>

<form method="post">
  {% csrf_token %}
  {{form |crispy}}
  <input class="btn btn-success" type="submit" value="Add" />
  <a class="btn btn-secondary" href="{% url 'allocation-detail' allocation.pk %}" role="button">Back to
    Allocation</a><br>
</form>
{% endblock %}

coldfront/core/allocation/templates/allocation/allocation_request_list.html
{% extends "common/base.html" %}
{% load crispy_forms_tags %}
{% load common_tags %}
{% load static %}


{% block title %}
Allocation Review New and Pending Requests
{% endblock %}


{% block content %}
<h2>Allocation Requests</h2>

<hr>

<p class="text-justify">
  For each allocation request below, there is the option to activate the allocation request and to view the allocation's detail page.
</p>

<p class="text-justify">
  By default, activating an allocation will make it active for {{ settings.ALLOCATION_DEFAULT_ALLOCATION_LENGTH }} days.
</p>

{% if allocation_list %}
  <div class="table-responsive">
    <table class="table table-sm">
      <thead>
        <tr>
          <th scope="col">#</th>
          <th scope="col">Requested</th>
          <th scope="col">Project Title</th>
          <th scope="col">PI</th>
          <th scope="col">Resource</th>
          {% if settings.PROJECT_ENABLE_PROJECT_REVIEW %}
            <th scope="col" class="text-nowrap">Project Review Status</th>
          {% endif %}
          <th scope="col">Status</th>
          <th scope="col">Actions</th>
        </tr>
      </thead>
      <tbody>
        {% for allocation in allocation_list %}
          <tr>
            <td>{{allocation.pk}}</td>
            <td>{{allocation_renewal_dates|get_value_from_dict:allocation.pk|default:allocation.created|date:"M. d, Y"}}</td>
            <td><a href="{% url 'project-detail' allocation.project.pk %}">{{allocation.project.title|truncatechars:50}}</a></td>
            <td>{{allocation.project.pi.first_name}} {{allocation.project.pi.last_name}}
              ({{allocation.project.pi.username}})</td>
            <td>{{allocation.get_parent_resource}}</td>
            {% if settings.PROJECT_ENABLE_PROJECT_REVIEW %}
              <td class="text-center">{{allocation.project|convert_status_to_icon}}</td>
            {% endif %}
            <td>{{allocation.status}}</td>
            <td class="text-nowrap">
                <form method="post" action="{% url 'allocation-detail' allocation.pk %}">
                  {% csrf_token %}
                  <input type="hidden" name="status" value="{{ allocation_status_active.id }}" />
                  <button type="submit" name="action" value="auto-approve" class="btn btn-success mr-1{% if allocation.get_information == '' %} confirm-activate{% endif %}">Approve</button>
                  <a href="{% url 'allocation-detail' allocation.pk %}" class="btn btn-primary mr-1">Details</a>
                </form>
            </td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
{% else %}
  <div class="alert alert-info">
    No new or pending allocation requests!
  </div>
{% endif %}

{% endblock %}

{% block javascript %}
{{ block.super }}
<script>
document.addEventListener('DOMContentLoaded', function() {
  $(document).on('click', '.confirm-activate', function(){
      return confirm('Are you sure you want to activate this allocation request without setting any allocation attributes?');
  })
});
</script>
{% endblock %}

coldfront/core/allocation/templates/allocation/allocation_update_invoice_note.html
{% extends "common/base.html" %}
{% load crispy_forms_tags %}
{% load static %}


{% block title %}
Update Allocation Invoice Note
{% endblock %}


{% block content %}
<h2>Update invoice note for allocation to {{allocation.get_resources_as_string}} for PI
  {{allocation.project.pi.username}}</h2>
<hr>

<form method="post">
  {% csrf_token %}
  {{ form|crispy }}
  <input class="btn btn-success" type="submit" value="Update">
  <a class="btn btn-secondary" href="{% url 'allocation-invoice-detail' object.allocation.pk %}" role="button">Cancel</a>
</form>
{% endblock %}