coldfront/config/urls.py
# SPDX-FileCopyrightText: (C) ColdFront Authors
#
# SPDX-License-Identifier: AGPL-3.0-or-later

"""
ColdFront URL Configuration
"""

import environ
import split_settings
from django.conf import settings
from django.contrib import admin
from django.core import serializers
from django.http import HttpResponse
from django.urls import include, path
from django.views.generic import TemplateView

import coldfront.core.portal.views as portal_views
from coldfront.config.env import ENV, PROJECT_ROOT

admin.site.site_header = "ColdFront Administration"
admin.site.site_title = "ColdFront Administration"

urlpatterns = [
    path("admin/", admin.site.urls),
    path("robots.txt", TemplateView.as_view(template_name="robots.txt", content_type="text/plain"), name="robots"),
    path("", portal_views.home, name="home"),
    path("center-summary", portal_views.center_summary, name="center-summary"),
    path("allocation-summary", portal_views.allocation_summary, name="allocation-summary"),
    path("allocation-by-fos", portal_views.allocation_by_fos, name="allocation-by-fos"),
    path("user/", include("coldfront.core.user.urls")),
    path("portal/", include("coldfront.core.portal.urls")),
    path("project/", include("coldfront.core.project.urls")),
    path("allocation/", include("coldfront.core.allocation.urls")),
    path("resource/", include("coldfront.core.resource.urls")),
]

if settings.GRANT_ENABLE:
    urlpatterns.append(path("grant/", include("coldfront.core.grant.urls")))

if settings.PUBLICATION_ENABLE:
    urlpatterns.append(path("publication/", include("coldfront.core.publication.urls")))

if settings.RESEARCH_OUTPUT_ENABLE:
    urlpatterns.append(path("research-output/", include("coldfront.core.research_output.urls")))

if "coldfront.plugins.api" in settings.INSTALLED_APPS:
    urlpatterns.append(path("api/", include("coldfront.plugins.api.urls")))

if "coldfront.plugins.iquota" in settings.INSTALLED_APPS:
    urlpatterns.append(path("iquota/", include("coldfront.plugins.iquota.urls")))

if "mozilla_django_oidc" in settings.INSTALLED_APPS:
    urlpatterns.append(path("oidc/", include("mozilla_django_oidc.urls")))

if "coldfront.plugins.slurm" in settings.INSTALLED_APPS:
    urlpatterns.append(path("slurm/", include("coldfront.plugins.slurm.urls")))

if "django_su.backends.SuBackend" in settings.AUTHENTICATION_BACKENDS:
    urlpatterns.append(path("su/", include("django_su.urls")))


def export_as_json(modeladmin, request, queryset):
    response = HttpResponse(content_type="application/json")
    serializers.serialize("json", queryset, stream=response)
    return response


admin.site.add_action(export_as_json, "export_as_json")

# Local urls overrides
local_urls = [
    # Local urls relative to coldfront.config package
    "local_urls.py",
    # System wide urls for production deployments
    "/etc/coldfront/local_urls.py",
    # Local urls relative to coldfront project root
    PROJECT_ROOT("local_urls.py"),
]

if ENV.str("COLDFRONT_URLS", default="") != "":
    # Local urls from path specified via environment variable
    local_urls.append(environ.Path(ENV.str("COLDFRONT_URLS"))())

for lu in local_urls:
    split_settings.tools.include(split_settings.tools.optional(lu))

coldfront/core/project/urls.py
# SPDX-FileCopyrightText: (C) ColdFront Authors
#
# SPDX-License-Identifier: AGPL-3.0-or-later

from django.urls import path

import coldfront.core.project.views as project_views

urlpatterns = [
    path("<int:pk>/", project_views.ProjectDetailView.as_view(), name="project-detail"),
    path("<int:pk>/archive", project_views.ProjectArchiveProjectView.as_view(), name="project-archive"),
    path("", project_views.ProjectListView.as_view(), name="project-list"),
    path(
        "project-user-update-email-notification/",
        project_views.project_update_email_notification,
        name="project-user-update-email-notification",
    ),
    path("archived/", project_views.ProjectArchivedListView.as_view(), name="project-archived-list"),
    path("create/", project_views.ProjectCreateView.as_view(), name="project-create"),
    path("<int:pk>/update/", project_views.ProjectUpdateView.as_view(), name="project-update"),
    path(
        "<int:pk>/add-users-search/", project_views.ProjectAddUsersSearchView.as_view(), name="project-add-users-search"
    ),
    path(
        "<int:pk>/add-users-search-results/",
        project_views.ProjectAddUsersSearchResultsView.as_view(),
        name="project-add-users-search-results",
    ),
    path("<int:pk>/add-users/", project_views.ProjectAddUsersView.as_view(), name="project-add-users"),
    path("<int:pk>/remove-users/", project_views.ProjectRemoveUsersView.as_view(), name="project-remove-users"),
    path(
        "<int:pk>/user-detail/<int:project_user_pk>",
        project_views.ProjectUserDetail.as_view(),
        name="project-user-detail",
    ),
    path("<int:pk>/review/", project_views.ProjectReviewView.as_view(), name="project-review"),
    path("project-review-list", project_views.ProjectReviewListView.as_view(), name="project-review-list"),
    path(
        "project-review-complete/<int:project_review_pk>/",
        project_views.ProjectReviewCompleteView.as_view(),
        name="project-review-complete",
    ),
    path("project-review/<int:pk>/email", project_views.ProjectReviewEmailView.as_view(), name="project-review-email"),
    path("<int:pk>/projectnote/add", project_views.ProjectNoteCreateView.as_view(), name="project-note-add"),
    path(
        "<int:pk>/project-attribute-create/",
        project_views.ProjectAttributeCreateView.as_view(),
        name="project-attribute-create",
    ),
    path(
        "<int:pk>/project-attribute-delete/",
        project_views.ProjectAttributeDeleteView.as_view(),
        name="project-attribute-delete",
    ),
    path(
        "<int:pk>/project-attribute-update/<int:project_attribute_pk>",
        project_views.ProjectAttributeUpdateView.as_view(),
        name="project-attribute-update",
    ),
]

coldfront/core/project/models.py
# SPDX-FileCopyrightText: (C) ColdFront Authors
#
# SPDX-License-Identifier: AGPL-3.0-or-later

import datetime
from enum import Enum

from django.contrib.auth import get_user_model
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.core.validators import MinLengthValidator
from django.db import models
from django.urls import reverse
from model_utils.models import TimeStampedModel
from simple_history.models import HistoricalRecords

from coldfront.core.field_of_science.models import FieldOfScience
from coldfront.core.project.signals import project_activate_user, project_remove_user
from coldfront.core.utils.common import import_from_settings
from coldfront.core.utils.validate import AttributeValidator

PROJECT_ENABLE_PROJECT_REVIEW = import_from_settings("PROJECT_ENABLE_PROJECT_REVIEW", False)


class ProjectPermission(Enum):
    """A project permission stores the user, manager, pi, and update fields of a project."""

    USER = "user"
    MANAGER = "manager"
    PI = "pi"
    UPDATE = "update"


class ProjectStatusChoice(TimeStampedModel):
    """A project status choice indicates the status of the project. Examples include Active, Archived, and New.

    Attributes:
        name (str): name of project status choice
    """

    class Meta:
        ordering = ("name",)

    class ProjectStatusChoiceManager(models.Manager):
        def get_by_natural_key(self, name):
            return self.get(name=name)

    name = models.CharField(max_length=64, unique=True)
    objects = ProjectStatusChoiceManager()

    def __str__(self):
        return self.name

    def natural_key(self):
        return (self.name,)


class Project(TimeStampedModel):
    """A project is a container that includes users, allocations, publications, grants, and other research output.

    Attributes:
        title (str): name of the project
        pi (User): represents the User object of the project's PI
        description (str): description of the project
        field_of_science (FieldOfScience): represents the field of science for this project
        status (ProjectStatusChoice): represents the ProjectStatusChoice of this project
        force_review (bool): indicates whether or not to force a review for the project
        requires_review (bool): indicates whether or not the project requires review
    """

    class Meta:
        ordering = ["title"]
        unique_together = ("title", "pi")

        permissions = (
            ("can_view_all_projects", "Can view all projects"),
            ("can_review_pending_project_reviews", "Can review pending project reviews"),
        )

    class ProjectManager(models.Manager):
        def get_by_natural_key(self, title, pi_username):
            return self.get(title=title, pi__username=pi_username)

    DEFAULT_DESCRIPTION = """
We do not have information about your research. Please provide a detailed description of your work and update your field of science. Thank you!
        """

    title = models.CharField(
        max_length=255,
    )
    pi = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
    )
    description = models.TextField(
        default=DEFAULT_DESCRIPTION,
        validators=[
            MinLengthValidator(
                10,
                "The project description must be > 10 characters.",
            )
        ],
    )

    field_of_science = models.ForeignKey(FieldOfScience, on_delete=models.CASCADE, default=FieldOfScience.DEFAULT_PK)
    status = models.ForeignKey(ProjectStatusChoice, on_delete=models.CASCADE)
    force_review = models.BooleanField(default=False)
    requires_review = models.BooleanField(default=True)
    history = HistoricalRecords()
    objects = ProjectManager()
    project_code = models.CharField(max_length=10, blank=True)
    institution = models.CharField(max_length=80, blank=True, default="None")

    def clean(self):
        """Validates the project and raises errors if the project is invalid."""

        if "Auto-Import Project".lower() in self.title.lower():
            raise ValidationError(
                'You must update the project title. You cannot have "Auto-Import Project" in the title.'
            )

        if (
            "We do not have information about your research. Please provide a detailed description of your work and update your field of science. Thank you!"
            in self.description
        ):
            raise ValidationError("You must update the project description.")

    @property
    def last_project_review(self):
        """
        Returns:
            ProjectReview: the last project review that was created for this project
        """
        project_review_query = self.projectreview_set.order_by("-created")
        if project_review_query:
            return project_review_query.first()
        else:
            return None

    @property
    def latest_grant(self):
        """
        Returns:
            Grant: the most recent grant for this project, or None if there are no grants
        """
        grant_query = self.grant_set.order_by("-modified")
        if grant_query:
            return grant_query.first()
        else:
            return None

    @property
    def latest_publication(self):
        """
        Returns:
            Publication: the most recent publication for this project, or None if there are no publications
        """
        publication_query = self.publication_set.order_by("-created")
        if publication_query:
            return publication_query.first()
        else:
            return None

    @property
    def needs_review(self):
        """
        Returns:
            bool: whether or not the project needs review
        """

        if self.status.name == "Archived":
            return False

        now = datetime.datetime.now(datetime.timezone.utc)

        if self.force_review is True:
            return True

        if not PROJECT_ENABLE_PROJECT_REVIEW:
            return False

        if self.requires_review is False:
            return False

        if self.projectreview_set.exists():
            last_review = self.projectreview_set.order_by("-created")[0]
            last_review_over_365_days = (now - last_review.created).days > 365
        else:
            last_review = None

        days_since_creation = (now - self.created).days

        if days_since_creation > 365 and last_review is None:
            return True

        if last_review and last_review_over_365_days:
            return True

        return False

    def user_permissions(self, user):
        """
        Params:
            user (User): represents the user whose permissions are to be retrieved

        Returns:
            list[ProjectPermission]: a list of the user's permissions for the project
        """

        if user.is_superuser:
            return list(ProjectPermission)

        user_conditions = models.Q(status__name__in=("Active", "New")) & models.Q(user=user)
        if not self.projectuser_set.filter(user_conditions).exists():
            return []

        permissions = [ProjectPermission.USER]

        if self.projectuser_set.filter(user_conditions & models.Q(role__name="Manager")).exists():
            permissions.append(ProjectPermission.MANAGER)

        if self.projectuser_set.filter(user_conditions & models.Q(project__pi_id=user.id)).exists():
            permissions.append(ProjectPermission.PI)

        if ProjectPermission.MANAGER in permissions or ProjectPermission.MANAGER in permissions:
            permissions.append(ProjectPermission.UPDATE)

        return permissions

    def has_perm(self, user, perm):
        """
        Params:
            user (User): user to check permissions for
            perm (ProjectPermission): permission to check for in user's list

        Returns:
            bool: whether or not the user has the specified permission
        """

        perms = self.user_permissions(user)
        return perm in perms

    def __str__(self):
        return self.title

    def natural_key(self):
        return (self.title,) + self.pi.natural_key()

    def add_user(self, user, role_choice, signal_sender=None):
        """
        Adds a user to the project.

        If a ProjectUser already exists, its role will be set to "Active" and its role updated.
        Otherwise, creates a new ProjectUser.

        Params:
            user (User): User to add.
            role_choice (ProjetUserRoleChoice): Role to give the project user.
            signal_sender (str): Sender for the `project_activate_user` signal.
        """
        user_status_obj = ProjectUserStatusChoice.objects.get(name="Active")

        project_user, _created = self.projectuser_set.update_or_create(
            user=user,
            defaults={
                "status": user_status_obj,
                "role": role_choice,
            },
        )

        project_activate_user.send(sender=signal_sender, project_user_pk=project_user.pk)

    def remove_user(self, user, signal_sender=None):
        """
        Marks a `ProjectUser` and any associated `AllocationUser`s as 'Removed'.

        Params:
            user (User|ProjectUser): User to remove.
            signal_sender (str): Sender for the `project_remove_user` and `allocation_remove_user` signals.

        Raises:
            ProjectUser.DoesNotExist: If `user` is a `User` and that user is not found in the Project.

        """
        if isinstance(user, ProjectUser):
            project_user = user
        elif isinstance(user, get_user_model()):
            project_user = self.projectuser_set.get(user=user)

        for active_allocation in self.allocation_set.filter(
            status__name__in=(
                "Active",
                "Denied",
                "New",
                "Paid",
                "Payment Pending",
                "Payment Requested",
                "Payment Declined",
                "Renewal Requested",

coldfront/core/user/forms.py
# SPDX-FileCopyrightText: (C) ColdFront Authors
#
# SPDX-License-Identifier: AGPL-3.0-or-later

from django import forms
from django.forms.widgets import CheckboxSelectMultiple
from django.utils.html import mark_safe


class UserSearchForm(forms.Form):
    CHOICES = [
        ("username_only", "Exact Username Only"),
        # ('all_fields', mark_safe('All Fields <a href="#" data-toggle="popover" data-trigger="focus" data-content="This option will be ignored if multiple usernames are specified."><i class="fas fa-info-circle"></i></a>')),
        (
            "all_fields",
            mark_safe(
                'All Fields <span class="text-secondary">This option will be ignored if multiple usernames are entered in the search user text area.</span>'
            ),
        ),
    ]
    q = forms.CharField(
        label="Search String",
        min_length=2,
        widget=forms.Textarea(attrs={"rows": 4}),
        help_text="Copy paste usernames separated by space or newline for multiple username searches!",
    )
    search_by = forms.ChoiceField(choices=CHOICES, widget=forms.RadioSelect(), initial="username_only")


class UserModelMultipleChoiceField(forms.ModelMultipleChoiceField):
    widget = CheckboxSelectMultiple

    def label_from_instance(self, obj):
        return f"{obj.first_name} {obj.last_name} ({obj.username})"

coldfront/core/project/templates/project/add_user_search_results.html
{% load crispy_forms_tags %}

<form action="{% url 'project-add-users' pk %}" method="post">
  {% csrf_token %}
  <div class="mb-3">
    {% if number_of_usernames_found %}
      <strong>Found {{number_of_usernames_found}} of
      {{number_of_usernames_searched}} usernames searched.</strong>
    {% elif matches %}
      <strong>Found {{matches|length}} match{{matches|length|pluralize:"es"}}.</strong>
    {% endif %}
    <br>
    {% if usernames_not_found %}
      Username{{usernames_not_found|length|pluralize}} missing from database
      {{usernames_not_found|length|pluralize:"is, are"}}: {{ usernames_not_found|join:", " }}.
    {% endif %}
    <br>
    {% if users_already_in_project %} The following
      user{{users_already_in_project|length|pluralize}}
      {{users_already_in_project|length|pluralize:"is, are"}} already in project:
      {{users_already_in_project|join:", "}}
    {% endif %}
  </div>

  {% if matches %}
    <div class="card bg-light mb-3 {{div_allocation_class}}">
      <div class="card-header">Available Allocations</div>
      <div class="card-body">
        <div class="table-responsive">
          <table class="table table-sm table-hover">
            <thead>
              <tr>
                <th><input type="checkbox" class="check" id="selectAllAllocations"></th>
                <th scope="col">#</th>
                <th scope="col">Resource</th>
                <th scope="col">Details</th>
                <th scope="col">Resource Type</th>
                <th scope="col">Status</th>
              </tr>
            </thead>
            <tbody>
              {% for form in allocation_formset %}
                <tr>
                  <td>{{ form.selected }}</td>
                  <td><a href="{% url 'allocation-detail' form.pk.value %}" target="_blank">{{ form.pk.value }}</a></td>
                  <td>{{ form.resource.value }}</td>
                  <td>{{ form.details.value }}</td>
                  <td>{{ form.resource_type.value }}</td>
                  <td>{{ form.status.value }}</td>
                </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>      
      </div>
      <div class="card-footer">
        <i class="fa fa-info-circle" aria-hidden="true"></i>
        Select allocations to add selected users to.
      </div>
      {{ allocation_formset.management_form }}
    </div>

    <div class="table-responsive">
      <table class="table table-sm table-hover">
        <thead>
          <tr>
            <th><input type="checkbox" class="check" id="selectAll"></th>
            <th scope="col">#</th>
            <th scope="col">Username</th>
            <th scope="col">First Name</th>
            <th scope="col">Last Name</th>
            <th scope="col">Email</th>
            <th scope="col">Role</th>
          </tr>
        </thead>
        <tbody>
          {% for form in formset %}
            <tr>
              <td>{{ form.selected }}</td>
              <td>{{ forloop.counter }}</td>
              <td>{{ form.username.value }}</td>
              <td>{{ form.first_name.value }}</td>
              <td>{{ form.last_name.value }}</td>
              <td>{{ form.email.value }}</td>
              <td>{{ form.role }}</td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
    {{ formset.management_form }}

    <input id="q" type="hidden" name="q" value="{{user_search_string}}">
    <input id="search_by" type="hidden" name="search_by" value="{{search_by}}">
    <div class="mb-3">
      {% if matches %}
        <button type="submit" class="btn btn-primary"><i class="fas fa-user-plus" aria-hidden="true"></i> Add Selected Users to Project</button>
      {% endif %}
      <a class="btn btn-secondary" href="{% url 'project-detail' pk %}" role="button">Back to Project</a><br>
    </div>
  {% else %}
    <div class="alert alert-info text-center">
      No results!
    </div>
  {% endif %}
</form>

<script>
  $("#selectAll").click(function () {
    $("input[name^='userform-']").prop('checked', $(this).prop('checked'));
  });

  $("input[name^='userform-']").click(function (ele) {
    var id = $(this).attr('id');
    if ( id != "selectAll") {
      $("#selectAll").prop('checked', false);
    }
  });

  $("#selectAllAllocations").click(function () {
    $("input[name^='allocationform-']").prop('checked', $(this).prop('checked'));
  });

  $("input[name^='allocationform-']").click(function (ele) {
    var id = $(this).attr('id');
    if ( id != "selectAllAllocations") {
      $("#selectAllAllocations").prop('checked', false);
    }
  });
</script>

{% comment %} if eula box is in focus, then required {% endcomment %}

coldfront/core/project/templates/project/project_add_users.html
{% extends "common/base.html" %}
{% load crispy_forms_tags %}
{% load static %}


{% block title %}
Add Users to Project
{% endblock %}


{% block content %}
<h2>Add users to project: {{project.title}}</h2>
<hr>

<div class="row">
  <div class="col">
    <form method="post" id="post-form">
      {% csrf_token %}
      {{ user_search_form|crispy }}
      <button id="search-button" type="submit" class="btn btn-success btn-block"><i class="fas fa-search" aria-hidden="true"></i> Search</button>
    </form>
  </div>
</div>

<br>
<div class="row">
  <div class="col" id="search_results">
      <div class="card border-light">
        <div class="card-body">
          <div id="search_results_inner"></div>
        </div>
      </div>
  </div>
</div>
<div class="row">
  <div class="col" id="selected_users">
      <div class="card border-light">
        <div class="card-body">
        </div>
      </div>
  </div>
</div>
{% endblock %}


{% block javascript %}
{{ block.super }}
<script>
document.addEventListener('DOMContentLoaded', function() {
  $('#post-form').on('submit', function(event){
    event.preventDefault();
    $('#search_results').show();
    $("#search_results_inner").html('<div class="alert alert-info text-center"><i class="fas fa-sync fa-spin fa-fw" aria-hidden="true"></i> Searching</div>')
    create_post();
  });

  function create_post() {
    q = $('#id_q').val().trim();
    search_by = $("#post-form input[type='radio']:checked").val();
    if (q.indexOf(' ') >= 0) {
      $("#id_id_search_by_0_1").prop("checked", true);
    }
    if (q.indexOf('\n') >= 0) {
      $("#id_id_search_by_0_1").prop("checked", true);
    }

    var pk = "{{ pk }}"
    $.ajax({
        url : "/project/" + pk + "/add-users-search-results/", // the endpoint
        type : "POST", // http method
        data : {
          q : q,
          search_by : search_by,
          csrfmiddlewaretoken: "{{ csrf_token }}"
        }, // data sent with the post request
        // handle a successful response
        success : function(data) {
            $('#post-text').val(''); // remove the value from the input
            $('#search_results').show();
            $('#search_results_inner').html(data);

        },

        // handle a non-successful response
        error : function(xhr,errmsg,err) {
            if(xhr.status == 403 || xhr.status == 401) {
                $('#search_results_inner').html("<div class='alert alert-danger'>Your session expired. Please login again. <a href='#' class='close'>&times;</a></div>");
            } else {
                $('#search_results_inner').html("<div class='alert alert-danger'>Oops! We have encountered an error: "+errmsg+
                    " <a href='#' class='close'>&times;</a></div>"); // add the error to the dom
            }
            console.log(xhr.status + ": " + xhr.responseText); // provide a bit more info about the error to the console
        }
    });
  };

    $('#search_results').hide();
    $('#selected_users').hide();
    $('[data-toggle="popover"]').popover();
});
</script>
{% endblock %}

coldfront/core/project/templates/project/project_archived_list.html
{% extends "common/base.html" %}
{% load crispy_forms_tags %}
{% load common_tags %}
{% load static %}


{% block title %}
Project List
{% endblock %}


{% block content %}
<div class="card mb-3 bg-light">
  <div class="card-body">
    <div class="float-left">
      <a class="btn btn-primary" href="{% url 'project-list' %}?{{filter_parameters}}" role="button"><i class="fas fa-arrow-left" aria-hidden="true"></i> Back to active projects</a>
    </div>
  </div>
</div>

<h2>Archived Projects</h2>
<hr>

{% if expand_accordion == "show" or project_list or user.is_superuser %}
  <div class="mb-3" id="accordion">
    <div class="card">
      <div class="card-header">
        <a id="expand_button" role="button" class="card-link " data-toggle="collapse" href="#collapseOne">
          <i class="fas fa-filter" aria-hidden="true"></i> Filter
          <i id="plus_minus" class="fas {{expand_accordion|get_icon}} float-right"></i>
        </a>
      </div>
      <div id="collapseOne" class="collapse {{expand_accordion}}" data-parent="#accordion">
        <div class="card-body">
          <form id="filter_form" method="GET" action="{% url 'project-archived-list' %}">
            {{ project_search_form|crispy }}
            <input type="submit" class="btn btn-primary" value="Search">
            <button id="form_reset_button" type="button" class="btn btn-secondary">Reset</button>
          </form>
        </div>
      </div>
    </div>
  </div>
  <hr>
{% endif %}

{% if project_list %}
  <strong>Projects: {{projects_count}}</strong>
  <div class="table-responsive">
    <table class="table table-sm">
      <thead>
        <tr>
          <th scope="col" class="text-nowrap">
            ID
            <a href="?order_by=id&direction=asc&{{filter_parameters}}"><i class="fas fa-sort-up" aria-hidden="true"></i><span class="sr-only">Sort ID asc</span></a>
            <a href="?order_by=id&direction=des&{{filter_parameters}}"><i class="fas fa-sort-down" aria-hidden="true"></i><span class="sr-only">Sort ID desc</span></a>
          </th>
          <th scope="col" class="text-nowrap">
            PI
            <a href="?order_by=pi__username&direction=asc&{{filter_parameters}}"><i class="fas fa-sort-up" aria-hidden="true"></i><span class="sr-only">Sort PI asc</span></a>
            <a href="?order_by=pi__username&direction=des&{{filter_parameters}}"><i class="fas fa-sort-down" aria-hidden="true"></i><span class="sr-only">Sort PI desc</span></a>
          </th>
          <th scope="col">Title and Description</th>
          <th scope="col" class="text-nowrap">
            Field of Science
            <a href="?order_by=field_of_science&direction=asc&{{filter_parameters}}"><i class="fas fa-sort-up" aria-hidden="true"></i><span class="sr-only">Sort Field of Science asc</span></a>
            <a href="?order_by=field_of_science&direction=des&{{filter_parameters}}"><i class="fas fa-sort-down" aria-hidden="true"></i><span class="sr-only">Sort Field of Science desc</span></a>
          </th>
          <th scope="col" class="text-nowrap">
            Status
            <a href="?order_by=status&direction=asc&{{filter_parameters}}"><i class="fas fa-sort-up" aria-hidden="true"></i><span class="sr-only">Sort Status asc</span></a>
            <a href="?order_by=status&direction=des&{{filter_parameters}}"><i class="fas fa-sort-down" aria-hidden="true"></i><span class="sr-only">Sort Status desc</span></a>
          </th>
        </tr>
      </thead>
      <tbody>
        {% for project in project_list %}
          <tr>
            {% if project.project_code %}
                <td><a href="/project/{{project.id}}/">{{ project.project_code }}</a></td>
            {% else %}
                <td><a href="/project/{{project.id}}/">{{ project.id }}</a></td>
            {% endif %}
            <td>{{ project.pi.username }}</td>
            <td style="text-align: justify; text-justify: inter-word;"><strong>Title: </strong> {{ project.title }}
              <br> <strong>Description: </strong>{{ project.description }}</td>
            <td>{{ project.field_of_science.description }}</td>
            <td>{{ project.status.name }}</td>
            {% if settings.PROJECT_INSTITUTION_EMAIL_MAP %}
                <p class="card-text text-justify"><strong>Institution: </strong>{{ project.institution }}</p>
            {% endif %}
          </tr>
        {% endfor %}
      </tbody>
    </table>
    {% if is_paginated %} Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
      <ul class="pagination float-right mr-3">
        {% if page_obj.has_previous %}
          <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}&{{filter_parameters_with_order_by}}">Previous</a></li>
        {% else %}
          <li class="page-item disabled"><a class="page-link" href="#">Previous</a></li>
        {% endif %}
        {% if page_obj.has_next %}
          <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}&{{filter_parameters_with_order_by}}">Next</a></li>
        {% else %}
          <li class="page-item disabled"><a class="page-link" href="#">Next</a></li>
        {% endif %}
      </ul>
    {% endif %}
  </div>
{% else %}
  <div class="alert alert-info">
    There are no archived projects!
  </div>
{% endif %}

{% endblock %}

coldfront/core/project/templates/project/project_attribute_create.html
{% extends "common/base.html" %}
{% load crispy_forms_tags %}
{% load common_tags %}
{% load static %}


{% block title %}
Add Project Attribute
{% endblock %}


{% block content %}
<h2>Adding project attribute to {{ project }}</h2>

<form method="post">
	{% csrf_token %}
	{{ form | crispy }}
	<input class="btn btn-success" type="submit" value="Add" />
	<a class="btn btn-secondary" href="{% url 'project-detail' project.pk %}" role="button">Back to
		Project</a><br>
</form>
{% endblock %}

coldfront/core/project/templates/project/project_update_form.html
{% extends "common/base.html" %}
{% load crispy_forms_tags %}
{% load static %}


{% block title %}
Update Project
{% endblock %}


{% block content %}
<form method="post">
  {% csrf_token %}
  {{ form|crispy }}
  <input class="btn btn-primary" type="submit" value="Save" />
  <a class="btn btn-secondary" href="{% url 'project-detail' object.pk %}" role="button">Cancel</a>
</form>

{% endblock %}